### ISSUE TITLE
Improve annotations

### ISSUE THREAD

**Issue by isinyaaa** [SuperLesson/SuperLesson#27]
Currently, SL annotates the transcribed text as PDF comments. That's not very flexible as many readers can't understand comments, or can't search them.

**Comment by isinyaaa** [comment]
We should probably try using a PDF engine to generate slides with the transcribed text. As discussed, we could look into [typst](https://github.com/typst/typst) ([python bindings library](https://github.com/messense/typst-py)). @alvesisaque can you look into this?

**Comment by isinyaaa** [comment]
@mmattana can you please suggest some way for matching slides with the transcribed text?

**Comment by mmattana** [comment]
> @mmattana can you please suggest some way for matching slides with the transcribed text?

@isinyaaa after the new data format (json) is in place, we will add the slide_number to each data entry. That entry could be done by association of a computer and a manual job. The computer job would roll the tframes in sequence and the operator should entre the slide_number of the corresponding frame in a input box. That would go on until the end of the tframes.

**Comment by mmattana** [comment]
Initial iteration for improve annotations formatting (in order of importance):
- Double spaces between paragraphs
- Margin that allow user to do small notes at sides, top and bottom of the page
- Interface that indicates to the user that the first and last period could be referring to past and next slide respectively (e.g. arrows at both end and beginning, each one pointing in opposition to each other )
- Sans serif font (could be Arial, Helvetica...)
- Very light gray background (could be #fbfafa)
