### ISSUE TITLE
Split functionality into poetry commands

### ISSUE THREAD

**Issue by rsgrava** [SuperLesson/SuperLesson#31]
As it currently stands, the scripts are executed by running:

`poetry run python src/main.py [lesson-id]`

This runs all the scripts in sequence, which can be undesirable. Ideally, we should be able to run each task separately.

This can be done in poetry with the execution of specific commands, such as:

`poetry run transcribe`
`poetry run transitions`

This is documented [here](https://python-poetry.org/docs/cli/#run).

**Comment by isinyaaa** [comment]
Sorry, I don't get why making them run in sequence should be undesirable. IMO we should have both options.

**Comment by isinyaaa** [comment]
> To be honest I think the current commands are going to be scrapped when we start refactoring code. As it stands right now, I've merely separated the code into seven commands corresponding to the seven original scripts.

Yeah you have a good point, as it stands we still don't have the right uncoupling between parts, so it's rather useful to be able to execute parts as needed, even for testing. But this interface would definitely be scraped as soon as we have something a little better to work with (say, a transcription pipeline that's totally independent from transitions and annotations). IMO that could turn into 3 or 4 commands soon, as is also suggested on #21.

**Comment by isinyaaa** [comment]
To define the steps and files used in each of them, we could use an enum definition with helper methods (or a class,  for that matter).
