### ISSUE TITLE
[BUG] Python dependence version in poetry

### ISSUE THREAD

**Issue by mmattana** [SuperLesson/SuperLesson#39]
Error for executing the program with poetry due to system python version

After running: 
$ poetry run python main.py [lesson_id]
I received an error message:
"The currently activated Python version 3.10.12 is not supported by the project (^3.11)."

Shouldn't poetry create an environment with all the dependencies (and its versions) it needs to run? 
Looks like at least for Python, it didn't work, it is trying to execute with my python system's version.

After I changed pyproject.toml
[tool.poetry.dependencies]
python = "^3.10"
It worked just fine.

 - OS: Ubuntu 22.04.03
 - Python version: 3.10.12
 - Version [e.g. 0.1.0 or a commit id in case you're running off the main branch

**Comment by rsgrava** [comment]
Poetry doesn't install python itself; rather, it uses the locally installed version of python to create a virtual environment. In my understanding, it is up to the user to provide the python installation.

We can automate this with the docker environment by having it install python 3.11, but that environment cannot currently be used for the tasks involving the usage of mpv.

Finally, we might also consider reducing the required version of python if 3.11 really isn't necessary.

**Comment by mmattana** [comment]
Solved at [#f2f0704](https://github.com/SuperLesson/SuperLesson/commit/f2f0704efed74b701ca5b84243db235d22684abd) by lowering python version dependency
