### ISSUE TITLE
[BUG] What if user doesn't have CUDA/Graphical processor 

### ISSUE THREAD

**Issue by mmattana** [SuperLesson/SuperLesson#41]
CUDA is the default option for running "single_file" method at "Transcribe" class
The program should automatically recognize if CUDA is not available and Run at CPU instead. 
After this option is implement, It may also be useful for the user to know in which option the transcription is running, so she/he can have a rough estimate of how long the process will take

**Comment by rsgrava** [comment]
I also believe we should automatically the presence of CUDA and default to cpu if it is not available.
This can be done with pytorch's [`torch.cuda.is_available()` method](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available).

However, I also believe this behavior should also be optionally overriddable by a `--use-cpu` flag.
