### ISSUE TITLE
Use whisper punctuation to generate cohesive paragraphs from transcription

### ISSUE THREAD

**Issue by isinyaaa** [SuperLesson/SuperLesson#51]
Currently, after inserting `tmarks`, the text is aggregated without taking sentence completeness into consideration. Fixing these sentences before ChatGPT reviews the text becomes a manual verification step, so let's try to automate some part of this.

**Comment by isinyaaa** [comment]
@rsgrava @alvesisaque @mmattana do you think we can skip the mpv part after this is solved?

**Comment by mmattana** [comment]
@isinyaaa I don't think we can trust whisper's punctuation to separate parts, so I'm skeptical that we can skip the verify tbreaks (mpv) process. I will bring more inputs on this subject by the next personal meeting.
