### ISSUE TITLE
Add script to transform a pdf with comment box to the new format

### ISSUE THREAD

**Issue by alvesisaque** [SuperLesson/SuperLesson#59]

**Comment by mmattana** [comment]
As commented in https://github.com/SuperLesson/SuperLesson/issues/27

Initial iteration for improve annotations formatting (in order of importance):
- Double spaces between paragraphs
- Margin that allow user to do small notes at sides, top and bottom of the page
- Interface that indicates to the user that the first and last period could be referring to past and next slide respectively (e.g. arrows at both end and beginning, each one pointing in opposition to each other )
- Sans serif font (could be Arial, Helvetica...)
- Very light gray background (could be #fbfafa)
