### ISSUE TITLE
Collect slide page numbers using tframes

### ISSUE THREAD

**Issue by isinyaaa** [SuperLesson/SuperLesson#78]
Page numbers can be gathered from the user by showing tframes in order and prompting for the respective slide number.

**Comment by mmattana** [comment]
@isinyaaa as we talked earlier, there is a special case to be considered:
Sometimes, the ppt/pdf available is not the same version as the one the teacher used at her/his class. The problem in that situation is that some text won't have a pdf page to be linked. In that case, the link text pdf should be either:
1) set to "None" or equivalent (which is different from just empty field ,the case in which the enumerate process was not made yet) or
2) that piece of text could be linked to another pdf page,  to be decided by the operator

**Comment by isinyaaa** [comment]
> 2. set to another pdf page, to be decided by the operator user

In here, do you mean that we should accept an arbitrary page of the default lecture notes document, or that we should get a reference to another document?

**Comment by mmattana** [comment]
We should accept an arbitrary page of the default lecture notes.
Some example:
text X -> pg 1
text Y -> pg 3
text Z -> (no equivalente found)

text Z should either:
   text Z -> None or
   text Z -> pg 3 (the operator decided "3", could be other)
So both text Y and text Z now are linked to pg 3. In this case, the string of text Z would be appended to the one of text Y

**Comment by isinyaaa** [comment]
An overview of what we agreed upon:

We proceed in the order of the transcription, asking frame by frame what the correspondence is.
- If the user responds with default (Enter), we follow the normal order (suggesting the next based on the last that appeared).
- If the user responds with 'n' or 'none', we discard the text.
- If the user responds with a number:
    - First, we check if it falls within the PDF limits [1, number of slides]; if it doesn't, we use the default (suggestion), as if the user had sent an empty response (the same applies if it is an invalid string that cannot be converted into a number).
    - If the number is valid—even if it is repeated for more than one text—we set that and suggest the next in sequence.
