### ISSUE TITLE
Create script to transform pdf with Box notes to notes in pdf file

### ISSUE THREAD

**Issue by alvesisaque** [SuperLesson/SuperLesson#85]

**Comment by mmattana** [comment]
rational of this script: will be used to update at least 30 lessons that were made in the old design format

@rsgrava please check with @alvesisaque to make sure we are bringing to this script the same design as the one resulted from the discussion at [issue 77](https://github.com/SuperLesson/SuperLesson/issues/77)

**Comment by isinyaaa** [comment]
Superseded by #100.
